### PR TITLE
66/json api

### PR DESCRIPTION
**Pull request by JanKoppe**
don't merge yet, work in progress.

### CODE REVIEW

**Comment by lkiesow** [comment]
Hi @JanKoppe,
I rebased this branch to the current state of `master` and continued your work on this. It is mostly finished but not quite yet. What is left is to add tests and maybe make error messages a bit more pretty.

**Comment by lkiesow** [comment]
Btw, the old commits are still in `66/json_api-backup`

**Comment by lkiesow** [comment]
This now returns valid json strings. Even for errors.
Also all REST endpoints are tested.

I think we should move some of the modules around since the names do not fit that well anymore but I would do that in another pull request:

- ui → web
- jsonapi → rest or api
- ui/\__init__ → web/ui
- ui/\__init__.app + ui/utils → web/app

That way, we should hopefully also be able to get rid of the ugly circular dependencies

**Comment by JanKoppe** [comment]
Hey @lkiesow, I've rebased this to current master and fixed a small issue with serializing of event data. This tests fine on Python 3.7 as well. Can you take a quick look at this? I'm not sure where we exactly left this PR, and I'd love to get this out in the very near future.

**Comment by lkiesow** [comment]
Generally looks good. I fixed a minor issue where you would get an internal server error when you don't send a content-type header but that's all I've found. I'll give it another look tomorrow but then likely merge it.

Long term, we should maybe add pagination to listing requests like `/api/events` but that's something we can still add later.

**Review by lkiesow — APPROVED** [review]
Finished the review. 
Worked as expected after a few very minor modifications.
I've also added some documentation for the API.

**Pull request merged**
