### PR TITLE
add agent state and centralized reporting to opencast

### PR DESCRIPTION
**Pull request by JanKoppe**
Tries to solve #64.

In the current state, everything works as advertised, _BUT_ agent state is not reported immediately, only periodically. This should be the case though.

### CODE REVIEW

**Comment by JanKoppe** [comment]
Everything works now, agent state is reported immediately on every change.

**Comment by JanKoppe** [comment]
need to add:
* immediate status reports
* update ui module to use agent state table

**Comment by JanKoppe** [comment]
After your review, this can be merged as is. @lkiesow

**Comment by lkiesow** [comment]
Looking at the logs, I think it might be a good idea to have the agents state as debug log only:

```
2017-03-07 22:46:41 INFO     [utils.py:90:get_service()] Endpoint for org.opencastproject.capture.admin: https://octestallinone.virtuos.uos.de/capture-admin
2017-03-07 22:46:41 INFO     [utils.py:90:get_service()] Endpoint for org.opencastproject.capture.admin: https://octestallinone.virtuos.uos.de/capture-admin
2017-03-07 22:46:41 INFO     [utils.py:90:get_service()] Endpoint for org.opencastproject.scheduler: https://octestallinone.virtuos.uos.de/recordings
2017-03-07 22:46:41 INFO     [utils.py:90:get_service()] Endpoint for org.opencastproject.ingest: https://octestallinone.virtuos.uos.de/ingest
2017-03-07 22:46:41 INFO     [utils.py:252:update_agent_state()] Reporting agentstate as offline
2017-03-07 22:46:41 INFO     [utils.py:90:get_service()] Endpoint for org.opencastproject.capture.admin: https://octestallinone.virtuos.uos.de/capture-admin
2017-03-07 22:46:41 INFO     [utils.py:159:register_ca()] pyca set to offline
2017-03-07 22:46:41 INFO     [schedule.py:109:control_loop()] No scheduled recording
2017-03-07 22:47:41 INFO     [utils.py:252:update_agent_state()] Reporting agentstate as idle
2017-03-07 22:47:41 INFO     [schedule.py:109:control_loop()] No scheduled recording
2017-03-07 22:47:41 INFO     [utils.py:159:register_ca()] pyca set to idle
2017-03-07 22:48:41 INFO     [utils.py:252:update_agent_state()] Reporting agentstate as idle
2017-03-07 22:48:41 INFO     [schedule.py:109:control_loop()] No scheduled recording
2017-03-07 22:49:41 INFO     [utils.py:252:update_agent_state()] Reporting agentstate as idle
2017-03-07 22:49:41 INFO     [schedule.py:107:control_loop()] Next scheduled recording: 2017-03-07 22:55:00
2017-03-07 22:50:41 INFO     [utils.py:252:update_agent_state()] Reporting agentstate as idle
2017-03-07 22:50:41 INFO     [schedule.py:107:control_loop()] Next scheduled recording: 2017-03-07 22:55:00
2017-03-07 22:51:41 INFO     [utils.py:252:update_agent_state()] Reporting agentstate as idle
2017-03-07 22:51:41 INFO     [schedule.py:107:control_loop()] Next scheduled recording: 2017-03-07 22:55:00


```

**Comment by lkiesow** [comment]
Can you rebase this branch, remove `pyca.db` and re-sign your commits?
A binary file should not be in the history.

**Comment by lkiesow** [comment]
Review done. Looks good so far.

I have added a patch with some minor fixes as well as some tests.

The two open points (mentioned above) are at the moment:

- Debug logging for setting agent state (not sure about that)
- `pyca.db` in repository

**Comment by JanKoppe** [comment]
I believe we can remove those status lines entirely, as `register_ca()` still does enough logging.

**Comment by JanKoppe** [comment]
Gee, sorry. Was fighting git a bit there. should probably squash and merge.

**Comment by lkiesow** [comment]
I'll rebase, clean-up and merge it tomorrow.
Do you want your commits to be signed?

If you do, then you will need to do an interactive rebase before I merge it.

**Comment by lkiesow** [comment]
Cleaned up the branch a bit. If you are Ok with this state, I will merge it like this later today.

**Comment by JanKoppe** [comment]
Yes, this is fine! Sorry for the delay.

**Comment by lkiesow** [comment]
Fixed all merge conflicts.
Will merge it if the travis tests pass.

**Pull request merged**
